### ISSUE TITLE
Security Check: Valid docker compose syntax is actually to have the ${} syntax allowed in every field. We want to allow this nowhere though

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#249]
This excerpt is a valid docker compose file

```
  app:
    image: ${PWD}
    restart: always
    links:
      - db
    volumes:
     - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${PWD}
      - MYSQL_DATABASE=asd
      - MYSQL_USER=$(PWD)
      - MYSQL_HOST=db
 ```

We need to check our code that nowhere we allow these ${} replacemets. The syntax checker should do that
