### ISSUE TITLE
Unclear fail of config

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#329]
@djesic This usage scenario fails on me and is not telling me why. I suppose because of the two machine providers.

can you, after your vacation, please implement a more sane error display. It took me > 5 minutes to understand what the issue was ...

```
postgresql:
# leave the host line empty if you do want to use Unix Domain socket connection
  host: secret
  user: secret
  dbname: secret
  password: secret

smtp:
  server: SMTP_SERVER
  sender: SMTP_SENDER
  port: SMTP_PORT
  password: SMTP_AUTH_PW
  user: SMTP_AUTH_USER

admin:
  # This address will get an email, when a new project was added through the frontend
  email: myemail@dev.local
  # no_emails: True will suppress all emails. Helpful in development servers
  no_emails: True

cluster:
  api_url: http://api.green-coding.internal:9142
  metrics_url: http://metrics.green-coding.internal:9142

machine:
  id: 2
  description: Quanta Leopard-DDR3 48-Core (IPMI)
  error_log_file: False

measurement:
  idle-time-start: 10
  idle-time-end: 5
  flow-process-runtime: 180
  phase-transition-time: 1
  metric-providers:

  # Please select the needed providers according to the working ones on your system
  # More info https://docs.green-coding.berlin/docs/measuring/metric-providers
  # Please activate and deactivate any provider in this list by uncommenting it.
  # Keep in mind that some reporters need separate installation steps to be found @
  # https://docs.green-coding.berlin/docs/installation/installation-overview/
  # You can ignore any line that starts with #---
    #--- Architecture - Linux Only
    linux:
    #--- Always-On - We recommend these providers to be always enabled
      cpu.utilization.procfs.system.provider.CpuUtilizationProcfsSystemProvider:
        resolution: 100
#      cpu.frequency.sysfs.core.provider.CpuFrequencySysfsCoreProvider:
#        resolution: 100
    #--- CGroupV2 - Turn these on if you have CGroupsV2 working on your machine
      cpu.utilization.cgroup.container.provider.CpuUtilizationCgroupContainerProvider:
        resolution: 100
      memory.total.cgroup.container.provider.MemoryTotalCgroupContainerProvider:
        resolution: 100
      network.io.cgroup.container.provider.NetworkIoCgroupContainerProvider:
        resolution: 100
    #--- RAPL - Only enable these if you have RAPL enabled on your machine
      cpu.energy.RAPL.MSR.component.provider.CpuEnergyRaplMsrComponentProvider:
        resolution: 100
      memory.energy.RAPL.MSR.component.provider.MemoryEnergyRaplMsrComponentProvider:
        resolution: 100
    #--- Machine Energy - These providers need special hardware / lab equipment to work
#      psu.energy.ac.gude.machine.provider.PsuEnergyAcGudeMachineProvider:
#        resolution: 100
#      psu.energy.ac.powerspy2.machine.provider.PsuEnergyAcPowerspy2MachineProvider:
#        resolution: 250
      psu.energy.ac.ipmi.machine.provider.PsuEnergyAcIpmiMachineProvider:
        resolution: 100
    #--- Sensors
#      lm_sensors.temperature.component.provider.LmSensorsTemperatureComponentProvider:
#        resolution: 100
      # Please change these values according to the names in '$ sensors'
#        chips: ['coretemp-isa-0000', 'coretemp-isa-0001']
#        features: ['Package id 0', 'Core 0', 'Core 1', 'Core 2', 'Core 3', 'Core 4', 'Core 5', 'Core 8', 'Core 9', 'Core 10', 'Core 11', 'Core 12', 'Core 13']
#      lm_sensors.fan.component.provider.LmSensorsFanComponentProvider:
#        resolution: 100
      # Please change these values according to the names in '$ sensors'
#        chips: ['thinkpad-isa-0000']
#        features: ['fan1', 'fan2']
    #--- Debug - These providers are just for development of the tool itself
#      cpu.time.cgroup.container.provider.CpuTimeCgroupContainerProvider:
#        resolution: 100
#      cpu.time.cgroup.system.provider.CpuTimeCgroupSystemProvider:
#        resolution: 100
#      cpu.time.procfs.system.provider.CpuTimeProcfsSystemProvider:
#        resolution: 100
    #--- Architecture - MacOS
    macos:
    #--- MacOS: On Mac you only need this provider. Please delete all others!
#      powermetrics.provider.PowermetricsProvider:
#        resolution: 100
    #--- Architecture - Common
    common:
    #--- Model based
      psu.energy.ac.sdia.machine.provider.PsuEnergyAcSdiaMachineProvider:
        resolution: 100
      #-- This is a default configuration. Please change this to your system!
#        CPUChips: 1
#        TDP: 65
#      psu.energy.ac.xgboost.machine.provider.PsuEnergyAcXgboostMachineProvider:
#        resolution: 100
      #-- This is a default configuration. Please change this to your system!
#        CPUChips: 2
#        HW_CPUFreq: 2500
#        CPUCores: 24
#        CPUThreads: 48
#        TDP: 120
#        HW_MemAmountGB: 32
#        Hardware_Availability_Year: 2015
  #--- END
```
