### ISSUE TITLE
Green Tests - Refactoring to Github Actions

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#83]
Currently we do have three YAML files for testing already.

Between these much code like setting up containers is reused.

We want to have Github Actions that we can reuse.

**Comment by ArneTR** [comment]
According to ChatGPT this could be a head start :)

```
name: My Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use action from another repository
        uses: owner/repository-name/path/to/action
```
